### ISSUE TITLE
Duplicate key on yaml

### ISSUE THREAD

**Issue by gspanos** [PacktPublishing/Mastering-Ansible-Second-Edition#1]
The `tasks` key appears twice here. That would cause only the last definition to be considered.
https://github.com/PacktPublishing/Mastering-Ansible-Second-Edition/blob/master/Chapter01/script.txt#L214

The README.md has the same duplicate key.

These examples are also depicted in the book.

**Comment by packt-pradeeps** [comment]
Please reopen the issue if you are facing any error.
